### PR TITLE
Update language server

### PR DESCRIPTION
**Pull request by deathaxe**
ship:

1. v1.39.12
2. net6.0 based language-server (instead of net472/mono)
3. arm64 compatible language-server

### CODE REVIEW

**Comment by rwols** [comment]
https://github.com/sublimelsp/LSP-OmniSharp/pull/31#discussion_r1365442197

Does this break current user's workflow when they don't have .NET 6 installed? I asked this a long time ago, but, I don't know if there's still a concern to be honest.

**Review by rwols — APPROVED** [review]
Let's just go with it.

**Comment by deathaxe** [comment]
It will break those, but mono has been deprecated long ago as well as .NET 4.7 on windows platform. Each recent Visual Studio ships .net6+ and it is an easy fix on Linux/MacOS as well. .NET 4.7 is also supported compile target on .net6+. So impact besides requiring .NET sdk should be rather low.

**Comment by rwols** [comment]
I tested this on Ubuntu and it now complains about a mono executable missing. I see there’s an OmniSharp file that, when given executable permissions, is executable. I want to have this minor issue fixed for Linux before making a release. I’ll do this myself but I do welcome PRs.

**Pull request merged**
